title: ClimaWatch
description: Monitoramento climático confiável para saúde, laboratórios e além.
baseurl: "" # deixe vazio se estiver usando o domínio padrão do GitHub Pages
url: "https://climawatch.github.io" # substitua pelo seu usuário

theme: null
# plugins:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock